version: 2
jobs:
  experiment:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - run: mkdir -p berlioz_workspace
      - run: echo "Hello, world!" > berlioz_workspace/echo-output
      - run: ls -la
      - run: ls -la berlioz_workspace/
  deliver_to_aws:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - setup_remote_docker
      - run:
          name: Install node and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version && npm -v
      - run:
          name: Install Berlioz CLI
          command: |
            sudo npm i -g berlioz
      - checkout
      - run: 
          name: Project File Structure
          command: ls -la
      - run: 
          name: Output Service Definitions
          command: sudo berlioz output-definitions
      - run: 
          name: Berlioz Login
          command: berlioz login --user $BERLIOZ_USER --pass $BERLIOZ_PASS
      - run: 
          name: Berlioz Build and Push Images
          command: sudo -E bash -c 'berlioz push --version-metadata-path workspace/berlioz-version-metadata'
      - run: 
          name: Berlioz Version Metadata
          command: cat workspace/berlioz-version-metadata
      - run: 
          name: Berlioz Trigger Run
          command: berlioz run --deployment test --cluster hello --region us-east-1 --version-metadata-path workspace/berlioz-version-metadata
      - run: 
          name: Berlioz Wait Ready
          command: berlioz wait --deployment test --cluster hello --region us-east-1 --timeout 600
      - run: 
          name: Berlioz Test Endpoint
          command: |
            url=$(berlioz endpoint --deployment test --cluster hello --region us-east-1 --endpoint web)
            echo "Service Url: $url"
            curl -s -S $url 2>&1
      # - run: 
      #     name: Berlioz Trigger Stop
      #     command: berlioz stop --deployment test --cluster hello --region us-east-1

workflows:
  version: 2
  deliver:
    jobs:
      - experiment
      # - deliver_to_aws