version: 2
jobs:
  # experiment:
  #   docker:
  #     - image: circleci/ruby:2.4.1-jessie
  #   steps:
  #     - checkout
  #     - run: mkdir -p berlioz_workspace
  #     - run: echo "Hello, world!" > berlioz_workspace/echo-output
  #     - run: ls -la
  #     - run: ls -la berlioz_workspace/
  #     - run: pwd
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #             - berlioz_workspace
  # follow_up:
  #   docker:
  #     - image: circleci/ruby:2.4.1-jessie
  #   steps:
  #     - attach_workspace:
  #         at: .
  #     - run: ls -la
  #     - run: ls -la berlioz_workspace/
  push_images:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - setup_remote_docker
      - run:
          name: Berlioz Setup
          command: curl -sL https://raw.githubusercontent.com/berlioz-the/berlioz/master/support/setup | sudo -E bash -
      - checkout
      - run: 
          name: Project File Structure
          command: ls -la
      - run: mkdir -p berlioz_workspace
      - run: 
          name: Output Service Definitions
          command: sudo berlioz output-definitions
      - run: 
          name: Berlioz Login
          command: berlioz login --user $BERLIOZ_USER --pass $BERLIOZ_PASS
      - run: 
          name: Berlioz Build and Push Images
          command: sudo -E bash -c 'berlioz push --version-metadata-path berlioz_workspace/version-metadata'
      - run: 
          name: Berlioz Version Metadata
          command: cat berlioz_workspace/version-metadata
      - persist_to_workspace:
          root: .
          paths:
              - berlioz_workspace

  test_in_cloud:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Berlioz Version Metadata
          command: cat berlioz_workspace/version-metadata
      - run:
          name: Berlioz Setup
          command: curl -sL https://raw.githubusercontent.com/berlioz-the/berlioz/master/support/setup | sudo -E bash -
      - run: 
          name: Berlioz Login
          command: berlioz login --user $BERLIOZ_USER --pass $BERLIOZ_PASS
      - run: 
          name: Berlioz Trigger Run
          command: berlioz run --deployment test --cluster hello --region us-east-1 --version-metadata-path berlioz_workspace/version-metadata
      - run: 
          name: Berlioz Wait Ready
          command: berlioz wait --deployment test --cluster hello --region us-east-1 --timeout 600
      - run: 
          name: Berlioz Test Endpoint
          command: |
            url=$(berlioz endpoint --deployment test --cluster hello --region us-east-1 --endpoint web)
            echo "Service Url: $url"
            curl -s -S $url 2>&1
      - run: 
          name: Berlioz Trigger Stop
          command: berlioz stop --deployment test --cluster hello --region us-east-1

  deploy_to_production:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: Berlioz Version Metadata
          command: cat berlioz_workspace/version-metadata
      - run:
          name: Berlioz Setup
          command: curl -sL https://raw.githubusercontent.com/berlioz-the/berlioz/master/support/setup | sudo -E bash -
      - run: 
          name: Berlioz Login
          command: berlioz login --user $BERLIOZ_USER --pass $BERLIOZ_PASS
      - run: 
          name: Berlioz Trigger Run
          command: berlioz run --deployment prod --cluster hello --region us-east-1 --version-metadata-path berlioz_workspace/version-metadata
      - run: 
          name: Berlioz Wait Ready
          command: berlioz wait --deployment prod --cluster hello --region us-east-1 --timeout 600
      - run: 
          name: Berlioz Test Endpoint
          command: |
            url=$(berlioz endpoint --deployment prod --cluster hello --region us-east-1 --endpoint web)
            echo "Service Url: $url"
            curl -s -S $url 2>&1

workflows:
  version: 2
  deliver:
    jobs:
      - push_images
      - test_in_cloud:
          requires:
            - push_images
      - deploy_to_production:
          requires:
            - push_images
            - test_in_cloud
      