version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1-jessie
    steps:
      - setup_remote_docker
      - run:
          name: Install node and npm
          command: |
            curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node --version && npm -v
      - run:
          name: Install Berlioz CLI
          command: |
            sudo npm i -g berlioz
      - checkout
      - run: 
          name: Project File Structure
          command: ls -la
      - run: 
          name: Service Definitions
          command: sudo berlioz output-definitions
      # - run: 
      #     name: Docker ps
      #     command: docker ps
      - run: 
          name: Docker build
          command: docker build

workflows:
  version: 2
  one_and_two:
    jobs:
      - one